-- MySQL Script generated by MySQL Workbench
-- Mon Apr 21 12:33:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apirelaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apirelaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apirelaciones` DEFAULT CHARACTER SET utf8 ;
USE `apirelaciones` ;

-- -----------------------------------------------------
-- Table `apirelaciones`.`cantantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirelaciones`.`cantantes` (
  `idcantante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcantante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apirelaciones`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirelaciones`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apirelaciones`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirelaciones`.`canciones` (
  `idcancion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `cantantes_idcantante` INT NULL,
  `genero_idgenero` INT NULL,
  PRIMARY KEY (`idcancion`),
  INDEX `fk_canciones_cantantes_idx` (`cantantes_idcantante` ASC) VISIBLE,
  INDEX `fk_canciones_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_cantantes`
    FOREIGN KEY (`cantantes_idcantante`)
    REFERENCES `apirelaciones`.`cantantes` (`idcantante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canciones_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `apirelaciones`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `apirelaciones`.`cantantes` (`nombre`) VALUES
 ('Jose Jose'),  ('Hector Lavoe'), ('Daddy Yanke'),('Michael Jacson'),("Romeo Santos");

 INSERT INTO `apirelaciones`.`genero` (`nombre`) VALUES
 ('Salsa'),('Bachata'),('Reguetoon'), ('Rock'),("Cumbia"),("Baladas");

INSERT INTO `apirelaciones`.`canciones` (`titulo`, `duracion`, `cantantes_idcantante`, `genero_idgenero`)
 VALUES ('Escarcha', '300', '2', '1'),('El Triste', '300', '1', '6'),('Rompe', '300', '3', '3');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
